export const PRODUCTS = [
  {
    id: "1",
    name: "Cupcake chocolate",
    oldPrice: 299,
    value: 749,
    image: require("../assets/products/choconfetes.png"),
    store: "BakeBliss",
    description: "Cupcake de chocolate c/ confetes. 250g",
  },
  {
    id: "2",
    name: "Cupcake brigadeiro",
    oldPrice: 189,
    value: 849,
    image: require("../assets/products/brigadeiro.jpg"),
    store: "BakeBliss",
    description: "Cupcake de brigadeiro. 250g",
  },
  {
    id: "3",
    name: "Cupcake morango",
    oldPrice: 189,
    value: 749,
    image: require("../assets/products/molango.png"),
    store: "BakeBliss",
    description: "Cupcake de morango. 250g",
  },
  {
    id: "4",
    name: "Cupcake céu azul",
    oldPrice: 169,
    value: 749,
    image: require("../assets/products/ceuazul.png"),
    store: "BakeBliss",
    description: "Cupcake de céu azul. 250g",
  },
  {
    id: "5",
    name: "Cupcake pamonha",
    oldPrice: 169,
    value: 749,
    image: require("../assets/products/pamonha.jpeg"),
    store: "BakeBliss",
    description: "Cupcake de pamonha. 250g",
  },
];
